### ISSUE TITLE
Editing the README

### ISSUE THREAD

**Issue by MadisonJMyers** [aloknsingh/ibm_r4ml_svm_classification#1]
Great job, Alok! This will be great, but there are a few edits I'm suggesting. Please see below:

- “Predicting the flight delay and building ML pipeline using scalable R package, R4ML” should be “Predicting flight delay and building an ML pipeline using R4ML”
- Now add the “scalable R package” back in the paragraph below making it: “In this developer journey we will use R4ML, a scalable R package, running on IBM Data Science Experience (DSX) to perform various Machine Learning exercises.” (I also corrected the grammar so be sure to use the corrected sentence above.)
- Suggested edit: change the second line in the first paragraph to: “For those users who are unfamiliar with the Data Science Experience, DSX is an interactive, collaborative, cloud-based environment where data scientists, developers, and others interested in data science can use tools (e.g., RStudio, Jupyter Notebooks, Spark, etc.) to collaborate, share, and gather insight from their data.”
- Suggested edit: add periods at the end of all bullet/number points
- Change “Leverage R4ML to do the big data exploratory analysis and data preperation” to “Leverage R4ML to conduct preprocessing and exploratory analysis with big data”
- Add an a before Support Vector Machine. (“Large Scale Model Training for classification using a Support Vector Machine.”)
- I would also change Large Scale to Large-scale, but that is my preference.
- Included Components should have a colon after (“Included Components:) I would do the same for “Featured Technologies”, “R4ML Key Features”, and “Steps”.
- “Open-source” does not always have the hyphen. I would add it to each to have consistency.
- “Featured technologies” should have technologies capitalized (Technologies)
- “R4ML” under “Featured technologies” should have a colon after (“R4ML:”)
- For number 4 in the listed steps that are highlighted (“4. Save and Share”) should be “4. Save and share” for consistency with uppercase.
- Under the expanded step “1. Sign up for the Data Science Experience” sentence two needs changed from “By signing up for the Data Science Experience, two services: DSX-Spark and DSX-ObjectStore will be created in your Bluemix account.” to “By signing up for the Data Science Experience, two services will be created in your Bluemix account: DSX-Spark and DSX-ObjectStore.”
- “Login to your Bluemix account” should be “Login or create your Bluemix account” in case they do not have one.
- “ If not already used, name your service DSX-Spark.” should be “If the name has not already been used, name your service DSX-Spark so that you can keep track of it.” Or you can just say that the user can leave the defaults.
- Same with the Object Storage line.
- “Create the Notebook 1” should just be “Create Notebook 1”
- In step 3 in the first 3 bullet points “this” should be changed to “which”. Just my preference.

I look forward to seeing the final product!

**Comment by aloknsingh** [comment]
Thanks. All the changes are incorporated.

**Comment by MadisonJMyers** [comment]
I just looked through your README and not one change that I noted above was implemented. Please implement. I go from the title down, in order, so you can follow along. I look forward to seeing the next version.

**Comment by aloknsingh** [comment]
Actually I have ci the code just now

**Comment by MadisonJMyers** [comment]
LGTM! Only things I noticed was that open source was not changed to "open-source" and "Save and Share" is sometimes lowercase sometimes upper case. Nothing too serious. Looks good and great work!

**Comment by aloknsingh** [comment]
I think you mentioned that is preference and both are ok :) 

I will change save/share.
